### ISSUE TITLE
tieba client 发帖会被系统自动删帖

### ISSUE THREAD

**Issue by kdurov** [linusyu/userScripts#1]
![2014-12-05 2 30 26](https://cloud.githubusercontent.com/assets/1715657/5311935/4a2e071a-7c8b-11e4-9b0e-bd1f85598d3a.png)

这样脚本就完全没法用了啊

**Comment by linusyu** [comment]
移步: http://firefoxbar.github.io/#userscripts  Tieba Client 0.9.4
